const SET_IS_FETCHING = "SET_IS_FETCHING";
const SET_IS_POSTING = "SET_IS_POSTING";
const USER_LOGOUT = "USER_LOGOUT";
const USER_LOGIN = "USER_LOGIN";
const FETCH_USER = "FETCH_USER";

export {
  SET_IS_FETCHING,
  SET_IS_POSTING,
  USER_LOGOUT,
  USER_LOGIN,
  FETCH_USER
};