const SET_IS_FETCHING = "SET_IS_FETCHING";
const SET_IS_POSTING = "SET_IS_POSTING";
const USER_LOGOUT = "USER_LOGOUT";
const USER_LOGIN = "USER_LOGIN";
const FETCH_USER = "FETCH_USER";

const SET_IS_LINKING = "SET_IS_LINKING";
const SET_IS_PLACING_ORDER = "SET_IS_PLACING_ORDER";
const LOGIN_INTO_ALPACA_ACCOUNT = "LOGIN_INTO_ALPACA_ACCOUNT";
const LOGOUT_FROM_ALPACA_ACCOUNT = "LOGOUT_FROM_ALPACA_ACCOUNT";

const SET_NAV_MENU_VISIBILITY = "SET_NAV_MENU_VISIBILITY";

const SET_IS_FETCHING_HISTORICAL_STOCK_PRICES = "SET_IS_FETCHING_HISTORICAL_STOCK_PRICES";
const SET_HISTORICAL_STOCK_PRICES = "SET_HISTORICAL_STOCK_PRICES";

const SET_IS_FETCHING_BUCKET_DATA = "SET_IS_FETCHING_BUCKET_DATA";
const SET_IS_FETCHING_BUCKETS = "SET_IS_FETCHING_BUCKETS";
const SET_IS_POSTING_BUCKET = "SET_IS_POSTING_BUCKET";
const UN_FOLLOW_BUCKET = "UN_FOLLOW_BUCKET";
const SET_IS_FOLLOWING = "SET_IS_FOLLOWING";
const GET_USER_BUCKETS = "GET_USER_BUCKETS";
const GET_BUCKET_DATA = "GET_BUCKET_DATA";
const FOLLOW_BUCKET = "FOLLOW_BUCKET";
const CREATE_BUCKET = "CREATE_BUCKET";
const UPDATE_BUCKET = "UPDATE_BUCKET";

export {
  SET_IS_FETCHING_HISTORICAL_STOCK_PRICES,
  SET_IS_FETCHING_BUCKET_DATA,
  SET_HISTORICAL_STOCK_PRICES,
  LOGOUT_FROM_ALPACA_ACCOUNT,
  LOGIN_INTO_ALPACA_ACCOUNT,
  SET_IS_FETCHING_BUCKETS,
  SET_NAV_MENU_VISIBILITY,
  SET_IS_POSTING_BUCKET,
  SET_IS_PLACING_ORDER,
  UN_FOLLOW_BUCKET,
  SET_IS_FOLLOWING,
  GET_USER_BUCKETS,
  GET_BUCKET_DATA,
  SET_IS_FETCHING,
  SET_IS_POSTING,
  SET_IS_LINKING,
  FOLLOW_BUCKET,
  CREATE_BUCKET,
  UPDATE_BUCKET,
  USER_LOGOUT,
  USER_LOGIN,
  FETCH_USER,
};
